### ISSUE TITLE
Error on creating new project with the template

### ISSUE THREAD

**Issue by DecampsRenan** [BearStudio/create-start-ui#12]
Initial issue was raised here: https://github.com/BearStudio/start-ui-native/issues/55

> When I run the command `npx create-start-ui --native start-up-proj`, I get this:
> ```
> ✖ An error occured while unziping template.
> Maybe this folder already exists: /home/obi/src/react-native/tmp/start-up-proj
> If this is the case, try removing it.
> ```

Version used: `0.1.0`

**Comment by DecampsRenan** [comment]
@obayit if you can send me the result of the following command:

```
ls -al /home/obi/src/react-native/tmp
```

And also the operating system you are using 😄

**Comment by obayit** [comment]
❯ ls -al /home/obi/src/react-native/tmp
```
total 12
drwxrwxr-x  3 obi obi 4096 Oct 15 12:16 .
drwxrwxr-x 19 obi obi 4096 Oct 14 15:48 ..
drwxrwxr-x  8 obi obi 4096 Oct 15 10:08 kittenTricks
-rw-rw-r--  1 obi obi    0 Oct 15 12:16 meh.txt
```

OS: Ubuntu 20.04

❯ node --version
v12.18.1

❯ npm --version
8.1.0

❯ npx --version
8.1.0

**Comment by DecampsRenan** [comment]
last thing, can you launch the command with the `--debug` flag ? the error should be more explicit (I hope ^^)

```bash
npx create-start-ui --debug --native start-up-proj
```

I'm testing with your node / npm / npx version to check what is wrong

**Comment by obayit** [comment]
with --debug it gave:
```
⚠  DEBUG LOG  

{
  debug: true,
  native: true,
  version: false,
  web: false,
  gitInit: true,
  help: false
}

✖ An error occured while unziping template.
Maybe this folder already exists: /home/obi/src/react-native/tmp/start-up-proj
If this is the case, try removing it.

```

**Comment by yoannfleurydev** [comment]
I think we should use the `tar.gz` version instead of the `zip` version. In the past, I had less problem with `tar` than `zip`. I guess the zip dependency we use is the origin of the problem.
