### ISSUE TITLE
The user cannot run yarn dev as soon as the create-start-ui cli is finished

### ISSUE THREAD

**Issue by DecampsRenan** [BearStudio/create-start-ui#19]
The idea is to allow the user to directly run `yarn dev` as soon as possible, without any error.

Some things are still missing to do that: 
- duplicate the `.env.example` file to a `.env` file (to prevent zod env parsing to fail)
- run db:build and db:seed scripts (to seed the database with default data)

**Comment by yoannfleurydev** [comment]
Closed by e0d6502f7729f5d65e8f05d0ada801f02ba40472
