### ISSUE TITLE
✨ We need a beautiful social preview ✨

### ISSUE THREAD

**Issue by DecampsRenan** [BearStudio/create-start-ui#5]

**Comment by yoannfleurydev** [comment]
The template given by GitHub:

![repository-open-graph-template](https://user-images.githubusercontent.com/3920615/134948747-2412a2ab-0462-4665-b730-dd3862c7bd7c.png)

**Comment by himanshu007-creator** [comment]
Hey!
I would like to work on this issue , can you describe a bit more about the project and give me the digital assets?
I would love to work on this one ^_^

**Comment by ivan-dalmet** [comment]
Sorry @himanshu007-creator I didn't see your message :/ 
We have internal assets for that, so it was quickly done. 
Thanks for your help!

<img width="1280" alt="create-start-ui" src="https://user-images.githubusercontent.com/9749061/135057833-2e83aa22-4544-4032-8d96-4c495090da9b.png">
